name: Deploy Store Microfrontend

on:
  push:
    branches: [main]
    paths:
      - 'store/**'
      - '.github/workflows/deploy-store.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          cd store
          npm ci

      - name: Build app
        run: |
          cd store
          npm run build -- --output-path=dist/store

      - name: Deploy to gh-pages (store/)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./store/dist/store
          destination_dir: store
          keep_files: true

